services:
  pet-feeder:
    build:
      context: .
      network: host
    network_mode: host
    env_file: .env
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 7890
