# -*- coding: utf-8 -*-
"""Tarea Clase 01/07 - Detección y Clasificación de Monedas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1588X8XZLJoP9lmQkQrvat3PvfkDPeplM

# Tarea 1: Detección y Clasificación de monedas
"""

# Importaciones necesarias
import matplotlib.pyplot as plt
import numpy as np
import cv2


# Función personalizada para reemplazar google.colab.patches.cv2_imshow localmente
def cv2_imshow(img):
    plt.figure(figsize=(6, 6))
    if len(img.shape) == 3:
        # Convierte de BGR (OpenCV) a RGB (Matplotlib)
        plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    else:
        # Muestra en escala de grises
        plt.imshow(img, cmap="gray")
    plt.axis("off")
    plt.show()


img = cv2.imread("./assets/coins1.jpeg")
cv2_imshow(img)

original = img.copy()

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2_imshow(gray)

clahe = cv2.createCLAHE(clipLimit=1.8, tileGridSize=(8, 8))

resultado = clahe.apply(gray)
cv2_imshow(resultado)

blur = cv2.GaussianBlur(resultado, (5, 5), 0)
cv2_imshow(blur)

_, binary = cv2.threshold(blur, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
cv2_imshow(binary)

# canny suele ser mejor para contornos
edges = cv2.Canny(blur, 50, 150)
cv2_imshow(edges)

# al ser monedas, tiene mayor sentido usar un kernel "redondo"
my_kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (7, 7))

# dilatacion y erosion
closing = cv2.morphologyEx(edges, cv2.MORPH_CLOSE, my_kernel, iterations=2)

cv2_imshow(closing)

contours, _ = cv2.findContours(closing, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

print("Monedas encontradas:", len(contours))

for c in contours:

    area = cv2.contourArea(c)

    if area < 40000:
        continue

    perimeter = cv2.arcLength(c, True)

    if perimeter == 0:
        continue

    x, y, w, h = cv2.boundingRect(c)

    aspect_ratio = w / h
    circularity = 4 * np.pi * area / (perimeter**2)

    if not (0.75 <= aspect_ratio <= 1.25):
        continue

    if circularity < 0.35:
        continue

    M = cv2.moments(c)

    if M["m00"] == 0:
        continue

    cx = int(M["m10"] / M["m00"])
    cy = int(M["m01"] / M["m00"])

    hull = cv2.convexHull(c)

    diameter = (w + h) / 2

    if diameter > 470:
        moneda = "2 Bs"
    elif diameter > 430:
        moneda = "1 Bs"
    elif diameter > 400:
        moneda = "50 ctvs"
    else:
        moneda = "5 Bs"

    cv2.drawContours(original, [c], -1, (0, 255, 0), 3)

    cv2.drawContours(original, [hull], -1, (255, 0, 0), 2)

    cv2.rectangle(original, (x, y), (x + w, y + h), (0, 255, 255), 2)

    cv2.circle(original, (cx, cy), 5, (0, 0, 255), -1)

    cv2.putText(
        original, moneda, (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (255, 0, 255), 2
    )

    print("Area:", area)
    print("Perimetro:", perimeter)
    print("Diametro:", diameter)
    print("Aspect ratio:", aspect_ratio)
    print("Circularidad:", circularity)
    print("Centro:", cx, cy)
    print("Clasificacion:", moneda)
    print("-------------------------")

plt.figure(figsize=(10, 10))

plt.subplot(3, 2, 1)
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title("Original")

plt.subplot(3, 2, 2)
plt.title("Gray")
plt.imshow(gray, cmap="gray")

plt.subplot(3, 2, 3)
plt.title("CLAHE + Blur")
plt.imshow(blur, cmap="gray")

plt.subplot(3, 2, 4)
plt.title("Canny")
plt.imshow(edges, cmap="gray")

plt.subplot(3, 2, 5)
plt.title("Closing ")
plt.imshow(closing, cmap="gray")

plt.subplot(3, 2, 6)
plt.title("Resultado")
plt.imshow(cv2.cvtColor(original, cv2.COLOR_BGR2RGB))

plt.show()
